#!/bin/sh

# Verbose and interactive mode
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -Iv" \
    ln="ln -iv" \
    mkd="mkdir -pv"

# Colorize always
alias \
    ls="ls --color=auto --group-directories-first -N" \
    grep="grep --color=auto" \
    egrep="egrep --color=auto" \
    fgrep="fgrep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# Variations on a theme
alias \
    ll="ls -lAhF" \
    ldot="ls -ldF .*" \
    l.="ls -dF .*" \
    l="ls -CF"

# Other useful shorthands
alias dud="du -d 1 -h" \           # display the size of files at depth 1
alias duf="du -sh" \               # display the size of files in the current dir
alias fd="find . -type d -name" \  # find directory with name
alias ff="find . -type f -name" \  # find file with name
alias sgrep="grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS}"  # ripgrep is better for this

alias cg='cd "$(git rev-parse --show-toplevel)"'  # cd to the top level of git repository

# Substitute neovim for vim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" rvim="nvim -Z" view="nvim -R" rview="nvim -RZ"

# Fix ssh in Alacritty when remote machine does not have termcap for it
_ssh() {
    [ "$TERM" = "alacritty" ] && TERM="xterm-256color"
    TERM="$TERM" ssh "$@"
}
alias ssh="_ssh"

# Create directory and cd into it
mkcd() { mkdir -p "$1" && cd "$1"; } 
